package com.capstone.ics.model;
// Generated Apr 16, 2016 4:53:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * AuditLog generated by hbm2java
 */
@Entity
@Table(name = "auditlog")
@Access(value = AccessType.PROPERTY)
public class AuditLog  implements java.io.Serializable {


     private IntegerProperty  auditId  = new SimpleIntegerProperty();
     private StringProperty user = new SimpleStringProperty(this, "USER");
     private StringProperty module = new SimpleStringProperty(this, "MODULE");
     private StringProperty activity = new SimpleStringProperty(this, "ACTIVITY");
     private StringProperty activityDetail = new SimpleStringProperty(this, "ACTIVITY_DETAIL");
     private ObjectProperty<Date> createdDate =  new SimpleObjectProperty<>(this, "CREATED_DATE");

    public AuditLog() {
    }

    public AuditLog(String user, String module, String activity, String activityDetail, Date createdDate) {
        setUser(user);
        setModule(module);
        setActivity(activity);
        setActivityDetail(activityDetail);
        setCreatedDate(createdDate);
    }
   
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "AUDIT_ID")
    public Integer getAuditId() {
        return auditIdIntegerProperty().get();
    }
    
    public void setAuditId(Integer auditId) {
        this.auditId.set(auditId);
    }
    
    public IntegerProperty auditIdIntegerProperty()
    {
        return this.auditId;
    }
    
    @Column(name = "USER")
    public String getUser() {
        return userProperty().get();
    }
    
    public void setUser(String user) {
        this.user.set(user);
    }
    
    public StringProperty userProperty()
    {
        return this.user;
    }
    
    /**
     *
     * @return
     */
    @Column(name = "MODULE")
    public String getModule() {
        return moduleProperty().get();
    }
    
    public void setModule(String module) {
        this.module.set(module);
    }
    
      public StringProperty moduleProperty()
    {
        return this.module;
    }
    
    @Column(name = "ACTIVITY")
    public String getActivity() {
        return activityProperty().get();
    }
    
    public void setActivity(String activity) {
        this.activity.set(activity);
    }
    
    public StringProperty activityProperty()
    {
        return this.activity;
    }
    @Column(name = "ACTIVITY_DETAIL")
    public String getActivityDetail() {
        return activityDetailProperty().get();
    }
    
    public void setActivityDetail(String activityDetail) {
        this.activityDetail.set(activityDetail);
    }
    
    public StringProperty activityDetailProperty()
    {
        return this.activityDetail;
    }
    
    @Column(name = "CREATED_DATE")
     @Temporal(javax.persistence.TemporalType.DATE)
    public Date getCreatedDate() {
        return dateProperty().get();
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate.set(createdDate);
    }

    public ObjectProperty<Date> dateProperty()
    {
        return this.createdDate;
    }


}


