package com.capstone.ics.model;
// Generated Mar 17, 2016 5:45:32 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Audit generated by hbm2java
 */
public class Audit  implements java.io.Serializable {


     private Integer pkAuditId;
     private Date timestamp;
     private Users users;
     private String level;
     private String activity;
     private String activityDetail;

    public Audit() {
    }

	
    public Audit(Users users) {
        this.users = users;
    }
    public Audit(Users users, String level, String activity, String activityDetail) {
       this.users = users;
       this.level = level;
       this.activity = activity;
       this.activityDetail = activityDetail;
    }
   
    public Integer getPkAuditId() {
        return this.pkAuditId;
    }
    
    public void setPkAuditId(Integer pkAuditId) {
        this.pkAuditId = pkAuditId;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    public String getActivity() {
        return this.activity;
    }
    
    public void setActivity(String activity) {
        this.activity = activity;
    }
    public String getActivityDetail() {
        return this.activityDetail;
    }
    
    public void setActivityDetail(String activityDetail) {
        this.activityDetail = activityDetail;
    }




}


