package com.capstone.ics.model;
// Generated Mar 22, 2016 9:24:22 PM by Hibernate Tools 4.3.1



/**
 * Credentials generated by hbm2java
 */
public class Credentials  implements java.io.Serializable {


     private Integer credentialsId;
     private int fkCrUserId;
     private String username;
     private String password;
     private Integer isAdministrator;

    public Credentials() {
    }

	
    public Credentials(int fkCrUserId, String username, String password) {
        this.fkCrUserId = fkCrUserId;
        this.username = username;
        this.password = password;
    }
    public Credentials(int fkCrUserId, String username, String password, Integer isAdministrator) {
       this.fkCrUserId = fkCrUserId;
       this.username = username;
       this.password = password;
       this.isAdministrator = isAdministrator;
    }
   
    public Integer getCredentialsId() {
        return this.credentialsId;
    }
    
    public void setCredentialsId(Integer credentialsId) {
        this.credentialsId = credentialsId;
    }
    public int getFkCrUserId() {
        return this.fkCrUserId;
    }
    
    public void setFkCrUserId(int fkCrUserId) {
        this.fkCrUserId = fkCrUserId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getIsAdministrator() {
        return this.isAdministrator;
    }
    
    public void setIsAdministrator(Integer isAdministrator) {
        this.isAdministrator = isAdministrator;
    }




}


