package com.capstone.ics.model;
// Generated Mar 17, 2016 5:45:32 PM by Hibernate Tools 4.3.1



/**
 * CredentialsId generated by hbm2java
 */
public class CredentialsId  implements java.io.Serializable {


     private int credentialsId;
     private int fkCrUserId;

    public CredentialsId() {
    }

    public CredentialsId(int credentialsId, int fkCrUserId) {
       this.credentialsId = credentialsId;
       this.fkCrUserId = fkCrUserId;
    }
   
    public int getCredentialsId() {
        return this.credentialsId;
    }
    
    public void setCredentialsId(int credentialsId) {
        this.credentialsId = credentialsId;
    }
    public int getFkCrUserId() {
        return this.fkCrUserId;
    }
    
    public void setFkCrUserId(int fkCrUserId) {
        this.fkCrUserId = fkCrUserId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CredentialsId) ) return false;
		 CredentialsId castOther = ( CredentialsId ) other; 
         
		 return (this.getCredentialsId()==castOther.getCredentialsId())
 && (this.getFkCrUserId()==castOther.getFkCrUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCredentialsId();
         result = 37 * result + this.getFkCrUserId();
         return result;
   }   


}


