package com.capstone.ics.model;
// Generated Mar 23, 2016 6:34:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Credentials generated by hbm2java
 */

@Entity
@Table(name = "credentials")
public class Credentials  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CREDENTIALS_ID")
     private Integer credentialsId;
    
    @Column(name = "FK_CR_USER_ID")
     private int fkCrUserId;
    
    @Column(name = "USERNAME")
     private String username;
    
    @Column(name = "PASSWORD")
     private String password;
    
    @Column(name = "IS_ADMINISTRATOR")
     private Integer isAdministrator;

    public Credentials() {
    }

	
    public Credentials(int fkCrUserId, String username, String password) {
        this.fkCrUserId = fkCrUserId;
        this.username = username;
        this.password = password;
    }
    public Credentials(int fkCrUserId, String username, String password, Integer isAdministrator) {
       this.fkCrUserId = fkCrUserId;
       this.username = username;
       this.password = password;
       this.isAdministrator = isAdministrator;
    }
   
    public Integer getCredentialsId() {
        return this.credentialsId;
    }
    
    public void setCredentialsId(Integer credentialsId) {
        this.credentialsId = credentialsId;
    }
    public int getFkCrUserId() {
        return this.fkCrUserId;
    }
    
    public void setFkCrUserId(int fkCrUserId) {
        this.fkCrUserId = fkCrUserId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getIsAdministrator() {
        return this.isAdministrator;
    }
    
    public void setIsAdministrator(Integer isAdministrator) {
        this.isAdministrator = isAdministrator;
    }




}


