package com.capstone.ics.model;
// Generated Mar 17, 2016 5:45:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * JobTitles generated by hbm2java
 */
public class JobTitles  implements java.io.Serializable {


     private Integer pkJobTitleCode;
     private String jobTitle;
     private String jobTitleDescription;
     private Set userses = new HashSet(0);

    public JobTitles() {
    }

    public JobTitles(String jobTitle, String jobTitleDescription, Set userses) {
       this.jobTitle = jobTitle;
       this.jobTitleDescription = jobTitleDescription;
       this.userses = userses;
    }
   
    public Integer getPkJobTitleCode() {
        return this.pkJobTitleCode;
    }
    
    public void setPkJobTitleCode(Integer pkJobTitleCode) {
        this.pkJobTitleCode = pkJobTitleCode;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public String getJobTitleDescription() {
        return this.jobTitleDescription;
    }
    
    public void setJobTitleDescription(String jobTitleDescription) {
        this.jobTitleDescription = jobTitleDescription;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


