package com.capstone.ics.model;
// Generated Mar 23, 2016 6:34:53 PM by Hibernate Tools 4.3.1



/**
 * JobTitles generated by hbm2java
 */
public class JobTitles  implements java.io.Serializable {


     private Integer pkJobTitleCode;
     private String jobTitle;
     private String jobTitleDescription;

    public JobTitles() {
    }

    public JobTitles(String jobTitle, String jobTitleDescription) {
       this.jobTitle = jobTitle;
       this.jobTitleDescription = jobTitleDescription;
    }
   
    public Integer getPkJobTitleCode() {
        return this.pkJobTitleCode;
    }
    
    public void setPkJobTitleCode(Integer pkJobTitleCode) {
        this.pkJobTitleCode = pkJobTitleCode;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public String getJobTitleDescription() {
        return this.jobTitleDescription;
    }
    
    public void setJobTitleDescription(String jobTitleDescription) {
        this.jobTitleDescription = jobTitleDescription;
    }




}


