package com.capstone.ics.model;
// Generated Mar 17, 2016 5:45:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RefItemCategories generated by hbm2java
 */
public class RefItemCategories  implements java.io.Serializable {


     private int pkItemCategoryCode;
     private String itemName;
     private String itemCategoryDescription;
     private Set inventoryItemses = new HashSet(0);

    public RefItemCategories() {
    }

	
    public RefItemCategories(int pkItemCategoryCode) {
        this.pkItemCategoryCode = pkItemCategoryCode;
    }
    public RefItemCategories(int pkItemCategoryCode, String itemName, String itemCategoryDescription, Set inventoryItemses) {
       this.pkItemCategoryCode = pkItemCategoryCode;
       this.itemName = itemName;
       this.itemCategoryDescription = itemCategoryDescription;
       this.inventoryItemses = inventoryItemses;
    }
   
    public int getPkItemCategoryCode() {
        return this.pkItemCategoryCode;
    }
    
    public void setPkItemCategoryCode(int pkItemCategoryCode) {
        this.pkItemCategoryCode = pkItemCategoryCode;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public String getItemCategoryDescription() {
        return this.itemCategoryDescription;
    }
    
    public void setItemCategoryDescription(String itemCategoryDescription) {
        this.itemCategoryDescription = itemCategoryDescription;
    }
    public Set getInventoryItemses() {
        return this.inventoryItemses;
    }
    
    public void setInventoryItemses(Set inventoryItemses) {
        this.inventoryItemses = inventoryItemses;
    }




}


