package com.capstone.ics.model;
// Generated Apr 14, 2016 11:58:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AssociationOverride;
import javax.persistence.AssociationOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;

/**
 * SiteItemsQuantity generated by hbm2java
 */
@Entity
@Table(name = "site_items_quantity")
@AssociationOverrides({
    @AssociationOverride(name = "id.item", joinColumns = @JoinColumn(name = "PK_ITEM_ID")),
    @AssociationOverride(name = "id.site", joinColumns = @JoinColumn(name = "PK_SITE_ID"))})
public class SiteItemsQuantity implements java.io.Serializable {

    private SiteItemsQuantityId id = new SiteItemsQuantityId();
    private InventoryItems inventoryItems;
    private Site site;
    private Integer itemQuantity;
    private Date createdDate;

    public SiteItemsQuantity() {
    }

    public SiteItemsQuantity(SiteItemsQuantityId id, InventoryItems inventoryItems, Site site) {
        this.id = id;
        this.inventoryItems = inventoryItems;
        this.site = site;
    }

    public SiteItemsQuantity(SiteItemsQuantityId id, InventoryItems inventoryItems, Site site, Integer itemQuantity, Date createdDate) {
        this.id = id;
        this.inventoryItems = inventoryItems;
        this.site = site;
        this.itemQuantity = itemQuantity;
        this.createdDate = createdDate;
    }

    @EmbeddedId
    public SiteItemsQuantityId getId() {
        return this.id;
    }

    public void setId(SiteItemsQuantityId id) {
        this.id = id;
    }

    @Transient
    public InventoryItems getInventoryItems() {
        return getId().getItem();
    }

    public void setInventoryItems(InventoryItems inventoryItems) {
        getId().setItem(inventoryItems);
    }

    @Transient
    public Site getSite() {
        return getId().getSite();
    }

    public void setSite(Site site) {
        getId().setSite(site);
    }

    @Column(name = "ITEM_QUANTITY")
    public Integer getItemQuantity() {
        return this.itemQuantity;
    }

    public void setItemQuantity(Integer itemQuantity) {
        this.itemQuantity = itemQuantity;
    }

    @Temporal(javax.persistence.TemporalType.DATE)
    @Column(name = "CREATED_DATE")
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        if (!(obj instanceof SiteItemsQuantity)) {
            return false;
        }

        SiteItemsQuantity other = (SiteItemsQuantity) obj;
        if (id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!id.equals(other.id)) {
            return false;
        }

        return true;

    }

}
