package com.capstone.ics.model;
// Generated Mar 23, 2016 6:34:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Site generated by hbm2java
 */
public class Site  implements java.io.Serializable {


     private Integer pkSiteId;
     private int fkSiteUserId;
     private String siteName;
     private String siteWebsite;
     private String siteOfficePhone;
     private String siteFax;
     private String siteAddressLine1;
     private String siteAddressLine2;
     private String siteCity;
     private String siteState;
     private String siteZipCode;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String createdBy;
     private String createdDate;

    public Site() {
    }

	
    public Site(int fkSiteUserId, String lastUpdatedBy, Date lastUpdatedDate, String createdBy, String createdDate) {
        this.fkSiteUserId = fkSiteUserId;
        this.lastUpdatedBy = lastUpdatedBy;
        this.lastUpdatedDate = lastUpdatedDate;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
    }
    public Site(int fkSiteUserId, String siteName, String siteWebsite, String siteOfficePhone, String siteFax, String siteAddressLine1, String siteAddressLine2, String siteCity, String siteState, String siteZipCode, String lastUpdatedBy, Date lastUpdatedDate, String createdBy, String createdDate) {
       this.fkSiteUserId = fkSiteUserId;
       this.siteName = siteName;
       this.siteWebsite = siteWebsite;
       this.siteOfficePhone = siteOfficePhone;
       this.siteFax = siteFax;
       this.siteAddressLine1 = siteAddressLine1;
       this.siteAddressLine2 = siteAddressLine2;
       this.siteCity = siteCity;
       this.siteState = siteState;
       this.siteZipCode = siteZipCode;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
    public Integer getPkSiteId() {
        return this.pkSiteId;
    }
    
    public void setPkSiteId(Integer pkSiteId) {
        this.pkSiteId = pkSiteId;
    }
    public int getFkSiteUserId() {
        return this.fkSiteUserId;
    }
    
    public void setFkSiteUserId(int fkSiteUserId) {
        this.fkSiteUserId = fkSiteUserId;
    }
    public String getSiteName() {
        return this.siteName;
    }
    
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }
    public String getSiteWebsite() {
        return this.siteWebsite;
    }
    
    public void setSiteWebsite(String siteWebsite) {
        this.siteWebsite = siteWebsite;
    }
    public String getSiteOfficePhone() {
        return this.siteOfficePhone;
    }
    
    public void setSiteOfficePhone(String siteOfficePhone) {
        this.siteOfficePhone = siteOfficePhone;
    }
    public String getSiteFax() {
        return this.siteFax;
    }
    
    public void setSiteFax(String siteFax) {
        this.siteFax = siteFax;
    }
    public String getSiteAddressLine1() {
        return this.siteAddressLine1;
    }
    
    public void setSiteAddressLine1(String siteAddressLine1) {
        this.siteAddressLine1 = siteAddressLine1;
    }
    public String getSiteAddressLine2() {
        return this.siteAddressLine2;
    }
    
    public void setSiteAddressLine2(String siteAddressLine2) {
        this.siteAddressLine2 = siteAddressLine2;
    }
    public String getSiteCity() {
        return this.siteCity;
    }
    
    public void setSiteCity(String siteCity) {
        this.siteCity = siteCity;
    }
    public String getSiteState() {
        return this.siteState;
    }
    
    public void setSiteState(String siteState) {
        this.siteState = siteState;
    }
    public String getSiteZipCode() {
        return this.siteZipCode;
    }
    
    public void setSiteZipCode(String siteZipCode) {
        this.siteZipCode = siteZipCode;
    }
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }




}


