package com.capstone.ics.model;
// Generated Apr 14, 2016 11:58:11 AM by Hibernate Tools 4.3.1

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;




/**
 * SiteItemsQuantityId generated by hbm2java
 */
@Embeddable
public class SiteItemsQuantityId  implements java.io.Serializable {

    private Site site;
    private InventoryItems item;

    public SiteItemsQuantityId() {
    }

    public SiteItemsQuantityId(Site site, InventoryItems item) {
        this.site = site;
        this.item = item;
    }

    @ManyToOne(cascade = CascadeType.ALL)
    public Site getSite() {
        return site;
    }

    public void setSite(Site site) {
        this.site = site;
    }

    @ManyToOne(cascade = CascadeType.ALL)
    public InventoryItems getItem() {
        return item;
    }

    public void setItem(InventoryItems item) {
        this.item = item;
    }
    

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SiteItemsQuantityId) ) return false;
		 SiteItemsQuantityId castOther = ( SiteItemsQuantityId ) other; 
         
		 return (this.getItem()==castOther.getItem())
 && (this.getSite()==castOther.getSite());
   }
   
   public int hashCode() {
         int result;         
         result= (site != null ? site.hashCode() : 0);
         result= 31* result + (item != null ? item.hashCode() : 0);
         return result;
   }   


}


