package com.capstone.ics.model;
// Generated Mar 22, 2016 9:24:22 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

    private Integer pkUserId;
    private int fkUserAddressId;
    private int fkJobTitleCode;
    private StringProperty firstName;
    private StringProperty lastName;
    private ObjectProperty<Date> birthDate;
    private StringProperty emailAddress;
    private StringProperty phoneNumber;
    private StringProperty gender;
    private StringProperty otherUserDetails;
    private StringProperty lastUpdatedBy;
    private ObjectProperty<Date> lastUpdatedDate;
    private StringProperty createdBy;
    private ObjectProperty<Date> createdDate;

    public Users() {
    }

    public Users(int fkUserAddressId, int fkJobTitleCode, String firstName, String lastName, Date birthDate, String emailAddress, String phoneNumber, String gender, Date lastUpdatedDate, String createdBy, Date createdDate) {
        this.fkUserAddressId = fkUserAddressId;
        this.fkJobTitleCode = fkJobTitleCode;
        this.firstName = new SimpleStringProperty(firstName);
        this.lastName = new SimpleStringProperty(lastName);
        this.birthDate = new SimpleObjectProperty<>(birthDate);
        this.emailAddress = new SimpleStringProperty(emailAddress);
        this.phoneNumber = new SimpleStringProperty(phoneNumber);
        this.gender = new SimpleStringProperty(gender);
        this.createdBy = new SimpleStringProperty(createdBy);
        this.createdDate = new SimpleObjectProperty<>(createdDate);
    }

    public Users(int fkUserAddressId, int fkJobTitleCode, String firstName, String lastName, Date birthDate, String emailAddress, String phoneNumber, String gender, String otherUserDetails, String lastUpdatedBy, Date lastUpdatedDate, String createdBy, Date createdDate) {
        this.fkUserAddressId = fkUserAddressId;
        this.fkJobTitleCode = fkJobTitleCode;
        this.firstName = new SimpleStringProperty(firstName);
        this.lastName = new SimpleStringProperty(lastName);
        this.birthDate = new SimpleObjectProperty<>(birthDate);
        this.emailAddress = new SimpleStringProperty(emailAddress);
        this.phoneNumber = new SimpleStringProperty(phoneNumber);
        this.gender = new SimpleStringProperty(gender);
        this.otherUserDetails = new SimpleStringProperty(otherUserDetails);
        this.lastUpdatedBy = new SimpleStringProperty(lastUpdatedBy);
        this.lastUpdatedDate = new SimpleObjectProperty<>(lastUpdatedDate);
        this.createdBy = new SimpleStringProperty(createdBy);
        this.createdDate = new SimpleObjectProperty<>(createdDate);
    }

    public Integer getPkUserId() {
        return this.pkUserId;
    }

    public void setPkUserId(Integer pkUserId) {
        this.pkUserId = pkUserId;
    }

    public int getFkUserAddressId() {
        return this.fkUserAddressId;
    }

    public void setFkUserAddressId(int fkUserAddressId) {
        this.fkUserAddressId = fkUserAddressId;
    }

    public int getFkJobTitleCode() {
        return this.fkJobTitleCode;
    }

    public void setFkJobTitleCode(int fkJobTitleCode) {
        this.fkJobTitleCode = fkJobTitleCode;
    }

    public String getFirstName() {
        return this.firstName.get();
    }

    public void setFirstName(String firstName) {
        this.firstName.set(firstName);
    }
    
    public StringProperty firstNameProperty()
    {
        return this.firstName;
    }

    public String getLastName() {
        return this.lastName.get();
    }

    public void setLastName(String lastName) {
        this.lastName.set(lastName);
    }
    
     public StringProperty lastNameProperty() {
        return this.lastName;
    }
    
    public Date getBirthDate() {
        return this.birthDate.get();
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate.set(birthDate);
    }
    
    public ObjectProperty<Date> birthdayProperty()
    {
        return this.birthDate;
    }

    public String getEmailAddress() {
        return this.emailAddress.get();
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress.set(emailAddress);
    }
    
    public StringProperty emailPropertyProperty()
    {
        return this.emailAddress;
    }

    public String getPhoneNumber() {
        return this.phoneNumber.get();
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber.set(phoneNumber);
    }
    
    public StringProperty phoneNumberProperty()
    {
        return this.phoneNumber;
    }

    public String getGender() {
        return this.gender.get();
    }

    public void setGender(String gender) {
        this.gender.set(gender);
    }
    
    public StringProperty genderProperty()
    {
        return this.gender;
    }

    public String getOtherUserDetails() {
        return this.otherUserDetails.get();
    }

    public void setOtherUserDetails(String otherUserDetails) {
        this.otherUserDetails.set(otherUserDetails);
    }
    
    public StringProperty otherDetailsProperty()
    {
        return this.otherUserDetails;
    }

    public String getLastUpdatedBy() {
        return this.lastUpdatedBy.get();
    }

    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy.set(lastUpdatedBy);
    }

    public StringProperty lastUpdatedByProperty()
    {
        return this.lastUpdatedBy;
    }
    
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate.get();
    }

    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate.set(lastUpdatedDate);
    }
    
    public ObjectProperty<Date>  getLastUPropertyDate() {
        return this.lastUpdatedDate;
    }


    public String getCreatedBy() {
        return this.createdBy.get();
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy.set(createdBy);
    }
    
    public StringProperty getCreatedByProperty() {
        return this.createdBy;
    }

    public ObjectProperty<Date>  getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate.set(createdDate);
    }

}
