package com.capstone.ics.model;
// Generated Mar 23, 2016 6:34:53 PM by Hibernate Tools 4.3.1



/**
 * UserAssignedToSiteId generated by hbm2java
 */
public class UserAssignedToSiteId  implements java.io.Serializable {


     private int fkUserid;
     private int fkSiteid;

    public UserAssignedToSiteId() {
    }

    public UserAssignedToSiteId(int fkUserid, int fkSiteid) {
       this.fkUserid = fkUserid;
       this.fkSiteid = fkSiteid;
    }
   
    public int getFkUserid() {
        return this.fkUserid;
    }
    
    public void setFkUserid(int fkUserid) {
        this.fkUserid = fkUserid;
    }
    public int getFkSiteid() {
        return this.fkSiteid;
    }
    
    public void setFkSiteid(int fkSiteid) {
        this.fkSiteid = fkSiteid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserAssignedToSiteId) ) return false;
		 UserAssignedToSiteId castOther = ( UserAssignedToSiteId ) other; 
         
		 return (this.getFkUserid()==castOther.getFkUserid())
 && (this.getFkSiteid()==castOther.getFkSiteid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkUserid();
         result = 37 * result + this.getFkSiteid();
         return result;
   }   


}


