package com.capstone.ics.model;
// Generated Mar 17, 2016 5:45:32 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer pkUserId;
     private JobTitles jobTitles;
     private UserAddresses userAddresses;
     private String firstName;
     private String lastName;
     private Date birthDate;
     private String emailAddress;
     private String phoneNumber;
     private String gender;
     private String otherUserDetails;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String createdBy;
     private String createdDate;
     private Set credentialses = new HashSet(0);
     private Set audits = new HashSet(0);
     private Set sites = new HashSet(0);
     private Set sites_1 = new HashSet(0);

    public Users() {
    }

	
    public Users(JobTitles jobTitles, UserAddresses userAddresses, String firstName, String lastName, Date birthDate, String emailAddress, String phoneNumber, String gender, Date lastUpdatedDate, String createdBy, String createdDate) {
        this.jobTitles = jobTitles;
        this.userAddresses = userAddresses;
        this.firstName = firstName;
        this.lastName = lastName;
        this.birthDate = birthDate;
        this.emailAddress = emailAddress;
        this.phoneNumber = phoneNumber;
        this.gender = gender;
        this.lastUpdatedDate = lastUpdatedDate;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
    }
    public Users(JobTitles jobTitles, UserAddresses userAddresses, String firstName, String lastName, Date birthDate, String emailAddress, String phoneNumber, String gender, String otherUserDetails, String lastUpdatedBy, Date lastUpdatedDate, String createdBy, String createdDate, Set credentialses, Set audits, Set sites, Set sites_1) {
       this.jobTitles = jobTitles;
       this.userAddresses = userAddresses;
       this.firstName = firstName;
       this.lastName = lastName;
       this.birthDate = birthDate;
       this.emailAddress = emailAddress;
       this.phoneNumber = phoneNumber;
       this.gender = gender;
       this.otherUserDetails = otherUserDetails;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.credentialses = credentialses;
       this.audits = audits;
       this.sites = sites;
       this.sites_1 = sites_1;
    }
   
    public Integer getPkUserId() {
        return this.pkUserId;
    }
    
    public void setPkUserId(Integer pkUserId) {
        this.pkUserId = pkUserId;
    }
    public JobTitles getJobTitles() {
        return this.jobTitles;
    }
    
    public void setJobTitles(JobTitles jobTitles) {
        this.jobTitles = jobTitles;
    }
    public UserAddresses getUserAddresses() {
        return this.userAddresses;
    }
    
    public void setUserAddresses(UserAddresses userAddresses) {
        this.userAddresses = userAddresses;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getOtherUserDetails() {
        return this.otherUserDetails;
    }
    
    public void setOtherUserDetails(String otherUserDetails) {
        this.otherUserDetails = otherUserDetails;
    }
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }
    public Set getCredentialses() {
        return this.credentialses;
    }
    
    public void setCredentialses(Set credentialses) {
        this.credentialses = credentialses;
    }
    public Set getAudits() {
        return this.audits;
    }
    
    public void setAudits(Set audits) {
        this.audits = audits;
    }
    public Set getSites() {
        return this.sites;
    }
    
    public void setSites(Set sites) {
        this.sites = sites;
    }
    public Set getSites_1() {
        return this.sites_1;
    }
    
    public void setSites_1(Set sites_1) {
        this.sites_1 = sites_1;
    }




}


