package com.capstone.ics.model;
// Generated Mar 22, 2016 9:24:22 PM by Hibernate Tools 4.3.1



/**
 * UserAssignedToSite generated by hbm2java
 */
public class UserAssignedToSite  implements java.io.Serializable {


     private UserAssignedToSiteId id;

    public UserAssignedToSite() {
    }

    public UserAssignedToSite(UserAssignedToSiteId id) {
       this.id = id;
    }
   
    public UserAssignedToSiteId getId() {
        return this.id;
    }
    
    public void setId(UserAssignedToSiteId id) {
        this.id = id;
    }




}


