package com.capstone.ics.model;
// Generated Mar 22, 2016 9:24:22 PM by Hibernate Tools 4.3.1



/**
 * UserAddresses generated by hbm2java
 */
public class UserAddresses  implements java.io.Serializable {


     private Integer pkAddressId;
     private String userAddressLine1;
     private String userAddressLine2;
     private String city;
     private String zipCode;
     private String state;
     private String country;

    public UserAddresses() {
    }

    public UserAddresses(String userAddressLine1, String userAddressLine2, String city, String zipCode, String state, String country) {
       this.userAddressLine1 = userAddressLine1;
       this.userAddressLine2 = userAddressLine2;
       this.city = city;
       this.zipCode = zipCode;
       this.state = state;
       this.country = country;
    }
   
    public Integer getPkAddressId() {
        return this.pkAddressId;
    }
    
    public void setPkAddressId(Integer pkAddressId) {
        this.pkAddressId = pkAddressId;
    }
    public String getUserAddressLine1() {
        return this.userAddressLine1;
    }
    
    public void setUserAddressLine1(String userAddressLine1) {
        this.userAddressLine1 = userAddressLine1;
    }
    public String getUserAddressLine2() {
        return this.userAddressLine2;
    }
    
    public void setUserAddressLine2(String userAddressLine2) {
        this.userAddressLine2 = userAddressLine2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


